spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://127.0.0.1:3306/mymall?serverTimezone=GMT%2B8&characterEncoding=utf-8&useSSL=false

mybatis:
  configuration:
    #驼峰 下划 互转
    map-underscore-to-camel-case: true
    #控制台日志配置
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapper/*.xml

#server:
 # servlet:
  #  session:
    #  timeout: 60